name: Spellcheck

on:
  pull_request:

jobs:
  spellcheck:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install Extra Dictionaries
        run: npm install
      - name: Run Spellcheck
        uses: streetsidesoftware/cspell-action@v6
        with:
          files: "**/*.{md,mdx}"
          suggestions: true
